version: '2'
services:
    wordpress:
        image: wordpress
        ports:
            - '8080:80'
        environment:
            WORDPRESS_DB_PASSWORD: abc123
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: abc123
